name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # Ou a branch que você usa para deploy

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Faz o checkout do seu código

      # REMOVA QUALQUER PASSO 'npm ci' OU 'npm run build'

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GESTAO_FINANCEIRA_COMPARTILHADE }}' # Certifique-se que o nome do secret está correto
          channelId: live # Opcional: para preview channels, etc.
          projectId: gestao-financeira-compartilhade # O ID do seu projeto Firebase
          # target: nome-do-seu-target-de-hosting # Se você tiver múltiplos sites no mesmo projeto Firebase
          # public: ./ # Opcional: se o index.html não estiver na raiz, especifique a pasta. Ex: ./public